/*
 * This source file was generated by the Gradle 'init' task
 */
package org.lb;

import java.io.IOException;
import org.lb.util.LoadBalancer;
import org.lb.util.config.ConfigProperties;

public class App {
  public static void main(String[] args) {
    LoadBalancer lb = new LoadBalancer(ConfigProperties.getPort());
    lb.addServers(ConfigProperties.getServers());
    ;

    /***
     * loadBalancer.addServer("localhost", 8081);
     * loadBalancer.addServer("localhost", 8082);
     */

    try {
      lb.start();
    } catch (IOException e) {
      e.printStackTrace();
    }
  }
}
